<br /><br />

<div class="panel">

  <div class="panel-body">

    <span class="subtitle pull-left">Your search returned <?php echo $this->Total;?> results:</span>

    <br clear="all" />

    <p align="center">
      <a href="<?php echo $this->baseUrl() ?>/result" class="btn btn-default btn-xs" type="button">Title View</a>
      <a href="<?php echo $this->baseUrl() ?>/result/list" class="btn btn-default btn-xs active" type="button">List View</a>
    </p>

    <br clear="all" />

    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Bull</th>
            <th>Bovine Id</th>
            <th>NAAB</th>
            <th>Registration Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($this->Data as $v) { ?>  
          <tr>
            <td><?php echo $v->f1 ; ?></td>
            <td><?php echo $v->f36 ; ?></td>
            <td><?php echo $v->f2 ; ?></td>
            <td><?php echo $v->f3 ; ?></td>
            <td></td>
          </tr>
        <?php } ?>  
        </tbody>
      </table>
    </div><!-- /.table-responsive -->

  </div>
</div>