<?php $sessionAdvSearchStep = new Zend_Session_Namespace('sessionAdvSearchStep'); ?>
<table class="table table-striped table-condensed" id="Holstein-Young">
  <tr align="center">
    <td align="center"><strong>Index</strong></td>
    <td align="center"><strong>More Than</strong></td>
    <td align="center"><strong>Health</strong></td>
    <td align="center"><strong>More Than</strong></td>
  </tr>
  <tr align="center">
    <td>NM$</td>
    <td>
      <select name="f61" id="f61" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="300" <?php if($sessionAdvSearchStep->parametros[f61] == 300) echo 'selected="selected"'; ?>>300</option>
        <option value="500" <?php if($sessionAdvSearchStep->parametros[f61] == 500) echo 'selected="selected"'; ?>>500</option>
        <option value="700" <?php if($sessionAdvSearchStep->parametros[f61] == 700) echo 'selected="selected"'; ?>>700</option>
        <option value="900" <?php if($sessionAdvSearchStep->parametros[f61] == 900) echo 'selected="selected"'; ?>>900</option>
      </select>
    </td>
    <td>PL</td>
    <td>
      <select name="f79" id="f79" class="form-control js-adv-select">
        <option value="">--Select--</option>
         <option value="0" <?php if($sessionAdvSearchStep->parametros[f79] == 0) echo 'selected="selected"'; ?>>0</option>
        <option value="3.00" <?php if($sessionAdvSearchStep->parametros[f79] == '3.00') echo 'selected="selected"'; ?>>3.00</option>
        <option value="5.00" <?php if($sessionAdvSearchStep->parametros[f79] == '5.00') echo 'selected="selected"'; ?>>5.00</option>
        <option value="7.00" <?php if($sessionAdvSearchStep->parametros[f79] == '7.00') echo 'selected="selected"'; ?>>7.00</option>
        <option value="9.00"<?php if($sessionAdvSearchStep->parametros[f79] == '9.00') echo 'selected="selected"'; ?> >9.00</option>
      </select>
    </td>
  </tr>
  <tr align="center">
    <td>TPI</td>
    <td>
      <select name="f51" id="f51" class="form-control js-adv-select">
        <option value="">--Select--</option>
       <option value="1900" <?php if($sessionAdvSearchStep->parametros[f51] == 1900) echo 'selected="selected"'; ?>>1900</option>
        <option value="2100" <?php if($sessionAdvSearchStep->parametros[f51] == 2100) echo 'selected="selected"'; ?>>2100</option>
        <option value="2300" <?php if($sessionAdvSearchStep->parametros[f51] == 2300) echo 'selected="selected"'; ?>>2300</option>
        <option value="2500" <?php if($sessionAdvSearchStep->parametros[f51] == 2500) echo 'selected="selected"'; ?>>2500</option>
      </select>
    </td>
    <td>SCS</td>
    <td>
      <select name="f77" id="f77" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="2.40" <?php if($sessionAdvSearchStep->parametros[f77] == '2.40') echo 'selected="selected"'; ?> >2.40</option>
        <option value="2.60" <?php if($sessionAdvSearchStep->parametros[f77] == '2.60') echo 'selected="selected"'; ?> >2.60</option>
        <option value="2.80" <?php if($sessionAdvSearchStep->parametros[f77] == '2.80') echo 'selected="selected"'; ?> >2.80</option>
        <option value="3.00" <?php if($sessionAdvSearchStep->parametros[f77] == '3.00') echo 'selected="selected"'; ?> >3.00</option>
        <option value="3.10" <?php if($sessionAdvSearchStep->parametros[f77] == '3.10') echo 'selected="selected"'; ?> >3.10</option>
      </select>
    </td>
  </tr>
  <tr align="center">
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="center"><strong>Fertility</strong></td>
    <td align="center">&nbsp;</td>
  </tr>
  <tr align="center">
    <td align="center"><strong>Product</strong></td>
    <td align="center">&nbsp;</td>
    <td>DPR</td>
    <td>
      <select name="f75" id="f75" class="form-control js-adv-select">
        <option value="">--Select--</option>
         <option value="0" <?php if($sessionAdvSearchStep->parametros[f75] == 0) echo 'selected="selected"'; ?> >0</option>
        <option value="1" <?php if($sessionAdvSearchStep->parametros[f75] == 1) echo 'selected="selected"'; ?> >1</option>
        <option value="2" <?php if($sessionAdvSearchStep->parametros[f75] == 2) echo 'selected="selected"'; ?> >2</option>
        <option value="3" <?php if($sessionAdvSearchStep->parametros[f75] == 3) echo 'selected="selected"'; ?> >3</option>
        <option value="4" <?php if($sessionAdvSearchStep->parametros[f75] == 4) echo 'selected="selected"'; ?>>4</option>
      </select>
    </td>
  </tr>
  <tr align="center">
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="center"><strong>Calving</strong></td>
    <td align="center">&nbsp;</td>
  </tr>
  <tr align="center">
    <td>PTAM</td>
    <td>
      <select name="f52" id="f52" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="0" <?php if($sessionAdvSearchStep->parametros[f52] == 0) echo 'selected="selected"'; ?> >0</option>
        <option value="500" <?php if($sessionAdvSearchStep->parametros[f52] == 500) echo 'selected="selected"'; ?> >500</option>
        <option value="1000" <?php if($sessionAdvSearchStep->parametros[f52] == 1000) echo 'selected="selected"'; ?> >1000</option>
        <option value="1500" <?php if($sessionAdvSearchStep->parametros[f52] == 1500) echo 'selected="selected"'; ?> >1500</option>
        <option value="2500" <?php if($sessionAdvSearchStep->parametros[f52] == 2500) echo 'selected="selected"'; ?> >2500</option>
        <option value="2900" <?php if($sessionAdvSearchStep->parametros[f52] == 2900) echo 'selected="selected"'; ?> >2900</option>
      </select>
    </td>
    <td>SCE</td>
    <td>
      <select name="f67" id="f67" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="4" <?php if($sessionAdvSearchStep->parametros[f67] == 4) echo 'selected="selected"'; ?>>4</option>
        <option value="6" <?php if($sessionAdvSearchStep->parametros[f67] == 6) echo 'selected="selected"'; ?>>6</option>
        <option value="8" <?php if($sessionAdvSearchStep->parametros[f67] == 8) echo 'selected="selected"'; ?>>8</option>
        <option value="10" <?php if($sessionAdvSearchStep->parametros[f67] == 10) echo 'selected="selected"'; ?>>10</option>
      </select>
    </td>
  </tr>
  <tr align="center">
    <td>MREL</td>
    <td>
      <select name="f60" id="f60" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="70" <?php if($sessionAdvSearchStep->parametros[f60] == 70) echo 'selected="selected"'; ?> >70</option>
        <option value="85" <?php if($sessionAdvSearchStep->parametros[f60] == 85) echo 'selected="selected"'; ?> >85</option>
        <option value="99" <?php if($sessionAdvSearchStep->parametros[f60] == 99) echo 'selected="selected"'; ?> >99</option>
      </select>
    </td>
    <td>DCE</td>
    <td>
      <select name="f69" id="f69" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="2" <?php if($sessionAdvSearchStep->parametros[f69] == 2) echo 'selected="selected"'; ?> >2</option>
        <option value="4" <?php if($sessionAdvSearchStep->parametros[f69] == 4) echo 'selected="selected"'; ?> >4</option>
        <option value="6" <?php if($sessionAdvSearchStep->parametros[f69] == 6) echo 'selected="selected"'; ?> >6</option>
        <option value="8" <?php if($sessionAdvSearchStep->parametros[f69] == 8) echo 'selected="selected"'; ?> >8</option>
</select>
    </td>
  </tr>
  <tr align="center">
    <td>PTAF</td>
    <td>
      <select name="f58" id="f58" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="0">0</option>
        <option value="40" <?php if($sessionAdvSearchStep->parametros[f58] == 40) echo 'selected="selected"'; ?> >40</option>
        <option value="80" <?php if($sessionAdvSearchStep->parametros[f58] == 80) echo 'selected="selected"'; ?> >80</option>
        <option value="100" <?php if($sessionAdvSearchStep->parametros[f58] == 100) echo 'selected="selected"'; ?> >100</option>
      </select>
    </td>
    <td align="center"><strong>Type</strong></td>
    <td align="center">&nbsp;</td>
  </tr>
  <tr align="center">
    <td>PTAF%</td>
    <td>
      <select name="f59" id="f59" class="form-control js-adv-select">
        <option value="">--Select--</option>
        <option value="0.00" <?php if($sessionAdvSearchStep->parametros[f59] == '0.00') echo 'selected="selected"'; ?> >0.00</option>
        <option value="0.10" <?php if($sessionAdvSearchStep->parametros[f59] == '0.10') echo 'selected="selected"'; ?> >0.10</option>
        <option value="0.20" <?php if($sessionAdvSearchStep->parametros[f59] == '0.20') echo 'selected="selected"'; ?> >0.20</option>
    </select></td>
      <td>PTAT</td>
      <td>
        <select name="f6" id="f6" class="form-control js-adv-select">
          <option value="">--Select--</option>
          <option value="0.00" <?php if($sessionAdvSearchStep->parametros[f6] == '0.00') echo 'selected="selected"'; ?> >0.00</option>
          <option value="1.00" <?php if($sessionAdvSearchStep->parametros[f6] == '1.00') echo 'selected="selected"'; ?> >1.00</option>
          <option value="2.00" <?php if($sessionAdvSearchStep->parametros[f6] == '2.00') echo 'selected="selected"'; ?> >2.00</option>
          <option value="3.00" <?php if($sessionAdvSearchStep->parametros[f6] == '3.00') echo 'selected="selected"'; ?> >3.00</option>
        </select>
      </td>
    </tr>
    <tr align="center">
      <td>PTAP</td>
      <td>
        <select name="f55" id="f55" class="form-control js-adv-select">
          <option value="">--Select--</option>
           <option value="0" <?php if($sessionAdvSearchStep->parametros[f55] == 0) echo 'selected="selected"'; ?> >0</option>
          <option value="30" <?php if($sessionAdvSearchStep->parametros[f55] == 30) echo 'selected="selected"'; ?> >30</option>
          <option value="50" <?php if($sessionAdvSearchStep->parametros[f55] == 50) echo 'selected="selected"'; ?> >50</option>
          <option value="70" <?php if($sessionAdvSearchStep->parametros[f55] == 70) echo 'selected="selected"'; ?> >70</option>
          <option value="90" <?php if($sessionAdvSearchStep->parametros[f55] == 90) echo 'selected="selected"'; ?> >90</option>
        </select>
      </td>
      <td>UDC</td>
      <td>
        <select name="f7" id="f7" class="form-control js-adv-select">
          <option value="">--Select--</option>
          <option value="0.00" <?php if($sessionAdvSearchStep->parametros[f7] == '0.00') echo 'selected="selected"'; ?> >0.00</option>
          <option value="1.00" <?php if($sessionAdvSearchStep->parametros[f7] == '1.00') echo 'selected="selected"'; ?> >1.00</option>
          <option value="2.00" <?php if($sessionAdvSearchStep->parametros[f7] == '2.00') echo 'selected="selected"'; ?> >2.00</option>
          <option value="3.00" <?php if($sessionAdvSearchStep->parametros[f7] == '3.00') echo 'selected="selected"'; ?> >3.00</option>
        </select>
      </td>
    </tr>
    <tr align="center">
      <td>PTAP%</td>
      <td>
        <select name="f56" id="f56" class="form-control js-adv-select">
          <option value="">--Select--</option>
          <option value="0.00" <?php if($sessionAdvSearchStep->parametros[f56] == '0.00') echo 'selected="selected"'; ?> >0.00</option>
          <option value="0.05" <?php if($sessionAdvSearchStep->parametros[f56] == '0.05') echo 'selected="selected"'; ?> >0.05</option>
          <option value="0.10" <?php if($sessionAdvSearchStep->parametros[f56] == '0.10') echo 'selected="selected"'; ?> >0.10</option>
          <option value="0.20" <?php if($sessionAdvSearchStep->parametros[f56] == '0.20') echo 'selected="selected"'; ?> >0.20</option>
        </select>
      </td>
      <td>FLC</td>
      <td>
        <select name="f9" id="f9" class="form-control js-adv-select">
          <option value="">--Select--</option>
         <option value="0" <?php if($sessionAdvSearchStep->parametros[f9] == 0) echo 'selected="selected"'; ?> >0</option>
          <option value="1" <?php if($sessionAdvSearchStep->parametros[f9] == 1) echo 'selected="selected"'; ?> >1</option>
          <option value="2" <?php if($sessionAdvSearchStep->parametros[f9] == 2) echo 'selected="selected"'; ?> >2</option>
          <option value="3" <?php if($sessionAdvSearchStep->parametros[f9] == 3) echo 'selected="selected"'; ?> >3</option>
        </select>
      </td>
    </tr>
</table>
