<?php 
$sessionCustomer = new Zend_Session_Namespace('sessionCustomer');

if($sessionCustomer->id) { 
    $add = 'checkbox-portfolio js-loginPortfolioAdv1';
} else {
	 $add = 'js-loginPortfolioAdv0';
}
?>

<table class="table table-hover tablesorter" id="myTable" align="center" style="font-size:11px;">
	<thead>
		<tr>
			<th></th>
			<th>NAAB</th>
			<th>Name</th>
			<th>NM$</th>
			<th>JPI</th>
			<th>CM$</th>
			<th>PTAM</th>
			<th>PTAF</th>
			<th>PTAF%</th>
			<th>PTAP</th>
			<th>CFP</th>
			<th>MREL</th>
			<th>PL</th>
			<th>SCS</th>
			<th>DPR</th>
			<th>PTAT</th>
			<th>UDC / JUI</th>
			<th>View</th>
		</tr>
	</thead>
	<tbody>
		<?php 
		foreach($this->Data as $v) {
			if ($v->abs == 1) {
				$class = 'class="info"';
			} else {
				$class = '';
			} 
			?>
			<tr <?php echo $class; ?> >
				<td>
					<input type="checkbox" name="email[]" class="js-email <?php echo $add; ?>" id="<?php echo $v->cod_bull ;?>" rel="<?php echo $v->cod_bull ;?>">
				</td>
				<td><?php echo $v->naab; ?></td>
				<td>
					<?php 
						if ($v->abs == 1) {
							echo '<b>'.$v->nome.'</b>';
						} else {
							echo $v->nome;
						} 
					?>
					<?php $this->Selo($v->cod_bull); ?>
				</td>
				<td><?php echo $this->MaskValue($v->f61,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f51,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f64,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f52,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f58,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f59,4,true); ?> %</td>
				<td><?php echo $this->MaskValue($v->f55,4,true); ?></td>
				<td></td>
				<td><?php echo $this->MaskValue($v->f60,4,false); ?> %</td>
				<td><?php echo $this->MaskValue($v->f79,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f77,4,false); ?></td>
				<td><?php echo $this->MaskValue($v->f75,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f6,4,true); ?></td>
				<td><?php echo $this->MaskValue($v->f7,4,true); ?></td>
				<td>
					<a href="<?php echo $this->baseUrl() ?>/result/details/id/<?php echo $v->cod_bull ;?>" class="btn btn-sm btn-primary">
						<i class="fa fa-plus-circle"></i> Details
					</a>
				</td>
			</tr>

			<?php } ?>
		</tbody>
	</table>