<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/touro/newvideo/id/<?php echo $this->Touro; ?>">
    <i class="fa fa-plus-circle fa-lg"></i> New Video
</a>

<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Bulls Videos</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Url</th>
                        <th>Published</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $this->YoutubeUrl($rs->video,true); ?></td>
                        <td><?php echo $rs->name; ?></td>
                        <td><?php echo $rs->video; ?></td>
                        <td class="center">
                            <?php 
                                if($rs->status == 1) echo '<span class="label label-success arrowed">Yes</label'; else echo '<span class="label">No</label';
                            ?>
                        </td>                     
                        <td class="center">
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Edit" href="<?php echo $this->BaseUrl() ?>/admin/touro/editvideo/id/<?php echo $rs->cod_video ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Delete" href="<?= $this->BaseUrl() ?>/admin/touro/deletevideo/id/<?php echo $rs->cod_video; ?>" >
                                <i class="fa fa-trash-o fa-lg"></i> 
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/col-->
</div><!--/row-->