<div class="panel">
	
	<div class="table-header"><i class="fa fa-th-large"></i> Your Account</div>
    
    <div id="msg-login" class="alert alert-danger" style="display:none;"></div>

	<br />
    <a href="<?php echo $this->baseUrl()?>/register/delete" class="btn btn-sm btn-danger">
		<i class="fa fa-trash-o"></i> <?php echo $this->Word(180);?>
	</a>

    <div class="col-xs-12"> 
    	<br />
    	<span>* Required Field</span>
		<?php echo $this->Form; ?>
	</div>

</div>