<div class="panel">

	<div class="col-xs-12 col-sm-12">

		<div class="login-box">
		

			<form class="form-horizontal" name="form-password" id="form-password" style="margin-top:20px;" action="<?= $this->baseUrl() ?>/register/forgot" method="post">

				<div class="input-prepend" title="Username">
					<span class="add-on">E-mail <i class="fa fa-user"></i></span>
					<input class="form-control" name="email" id="email" type="text" placeholder="E-mail"/>
				</div>

				<div class="clearfix"></div>

				<div class="btn-group button-login">
					<button type="submit" id="bt-password" class="btn btn-primary"><i class="fa fa-share"></i> Send Password</button>
				</div>
			</form>

		</div>

	</div>


</div>