<div class="panel">

	<?php if ($this->Error == 1 or $this->Error == 2) {?>

		<div class="alert alert-danger">
			
			<?php 

				if ($this->Error == 1) {
					echo 'User unknown, please register';
				} elseif ($this->Error == 2) {
					echo 'Incorrect password, please re-enter your password or click on the "Forgot Password" to retrieve your password';
				}
			?>

		</div>

	<?php } ?>

	<div class="col-xs-12 col-sm-12">

		<div class="login-box">

			<div style="text-align:center; margin-top:20px;">
				<a href="#" id="loginface" class="btn btn-primary"><i class="fa fa-facebook-square fa-lg"></i> Login with Facebook </a>

				<br /><br />

				OR
			</div>

			
			<form class="form-horizontal" id="form-login" style="margin-top:20px;" action="<?= $this->baseUrl() ?>/register/login" method="post">

				<div class="input-prepend" title="Username">
					<span class="add-on"><i class="fa fa-user"></i></span>
					<input class="form-control" name="usuario" id="usuario" type="text" placeholder="E-mail"/>
				</div>

				<div class="clearfix"></div>

				<div class="input-prepend" title="Password">
					<span class="add-on"><i class="fa fa-lock"></i></span>
					<input class="form-control" name="senha" id="senha" type="password" placeholder="Password"/>
				</div>
				<div class="clearfix"></div>
				
				<label>
            		<input type="checkbox" name="remember" value="1" />
            		Keep me logged in
        		</label>
				<br />

				
				<a href="<?php echo $this->baseUrl() ?>/register/forgot" class="btn btn-primary"><i class="fa fa-key"></i> Forgot Password</a>

				<br />

				<div class="btn-group button-login">
					<button type="submit" class="btn btn-primary" id="btn-login"><i class="fa fa-power-off"></i> Login</button>
				</div>
			</form>

		</div>

	</div>


</div>