<div class="jumbotron">
	<h2><?php echo $this->Word(6);?></h2>
	<p><?php echo $this->Word(7);?></p>
	<p align="center">

		<button type="button" rel="step1+step1+<?php echo $this->Word(75);?>" value="Dairy" class="btn btn-default btn-lg step"><?php echo $this->Word(75);?></button>

		<a href="http://www.absglobal.com/beef" target="_blank" class="btn btn-default btn-lg" value="Beef" role="button"><?php echo $this->Word(76);?></a>
	</p>
</div>