<div class="panel">

	<div class="panel-body">

		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl() ?>/index">Home</a></li>
			<li class="active">Dairy / Beef</li>
		</ol>

		<?php echo $this->render('render/sidebar.phtml'); ?>


		<div class="col-xs-12 col-sm-6 col-md-9">

			<p>

				Welcome to the ABS Global <br />
				Bull Search Application.<br /><br />

				<a rel="step1+step2+<?php echo $this->Word(75);?>" class="btn btn-default btn-lg step" value="Dairy" role="button"><?php echo $this->Word(75);?></a>
				<!--<a rel="step1+step2+<?php echo $this->Word(76);?>" class="btn btn-default btn-lg step" value="Beef" role="button"><?php echo $this->Word(76);?></a>-->
				<a href="http://www.absglobal.com/beef" target="_blank" class="btn btn-default btn-lg" value="Beef" role="button"><?php echo $this->Word(76);?></a>
				
			</p>

		</div>

	</div>
</div>