<div class="panel">

	<div class="panel-body">

		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl() ?>/index">Home</a></li>
			<li class="active">Dairy / Beef</li>
		</ol>

		<?php echo $this->render('render/sidebar.phtml'); ?>


		<div class="col-xs-12 col-sm-6 col-md-9">

            <span class="subtitle">Choose your Sire Type:</span>
            <br /><br />
            
            <p>

             	<button type="button" rel="step3+step4+Daughter Proven" class="btn btn-default btn-lg step btn-tooltip" value="daughter_proven" role="button" data-toggle="tooltip" data-placement="top" title="Genomically tested bulls with milking daughters contributing to their genetic evaluations.">Daughter Proven</button>

            	<button type="button" rel="step3+step4+Genomic Young Sires" class="btn btn-default btn-lg step btn-tooltip" value="genomic_young_sires" role="button" data-toggle="tooltip" data-placement="top" title="Genomically tested young sires awaiting milking daughter proof information.">Genomic Young Sires</button>

            	<button type="button" rel="step3+step4+All" class="btn btn-default btn-lg step btn-tooltip" value="all" role="button" data-toggle="tooltip" data-placement="top" title="Both Daughter Proven and Genomic Young Sires">All</button>
            </p>

        </div>

	</div>
</div>

