<div class="panel">

	<div class="panel-body">

		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl() ?>/index">Home</a></li>
			<li class="active"><?php echo $this->Word(75);?> / <?php echo $this->Word(76);?></li>
		</ol>

		<?php echo $this->render('render/sidebar.phtml'); ?>


		<div class="col-xs-12 col-sm-6 col-md-9">

			<span class="subtitle"><?php echo $this->Word(82);?></span>
            <br /><br />
            <p>

            	<button type="button" rel="step2+step3+<?php echo $this->Word(83);?>" value="Holstein" class="btn btn-default btn-lg step"><?php echo $this->Word(83);?></button>

            	<button type="button" rel="step2+step3+<?php echo $this->Word(84);?>" class="btn btn-default btn-lg step" value="Jersey"><?php echo $this->Word(84);?></button>

            	<button type="button" rel="step2+step3+<?php echo $this->Word(85);?>" class="btn btn-default btn-lg step" value="Other Breeds"><?php echo $this->Word(85);?></button>

            </p>

		</div>

	</div>
</div>