<div class="panel">

	<div class="panel-body">

		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl() ?>/index">Home</a></li>
			<li class="active">Dairy / Beef</li>
		</ol>

		<?php echo $this->render('render/sidebar.phtml'); ?>


		<div class="col-xs-12 col-sm-6 col-md-9">

			<p>

				Welcome to the ABS Global <br />
				Bull Search Application.<br /><br />

				<a class="btn btn-lg btn-default" href="<?php echo $this->baseUrl() ?>/index/step2" role="button"><?php echo $this->Word(8);?></a>

				<a class="btn btn-lg btn-default" href="<?php echo $this->baseUrl() ?>/advanced" role="button"><?php echo $this->Word(9);?></a>
				
			</p>

		</div>

	</div>
</div>