<div class="panel">

	<div class="panel-body">

		<ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl() ?>/index">Home</a></li>
			<li class="active"><?php echo $this->Word(75);?> / <?php echo $this->Word(76);?></li>
		</ol>

		<?php echo $this->render('render/sidebar.phtml'); ?>


		<div class="col-xs-12 col-sm-6 col-md-9">

			<span class="subtitle"><?php echo $this->Word(82);?></span>
            <br /><br />
            <p>
              <a rel="step2+step3+<?php echo $this->Word(83);?>" class="btn btn-default btn-lg step" value="Holstein" role="button"><?php echo $this->Word(83);?></a>
              <a rel="step2+step3+<?php echo $this->Word(84);?>" class="btn btn-default btn-lg step" value="Jersey" role="button"><?php echo $this->Word(84);?></a>
              <a rel="step2+step3+<?php echo $this->Word(85);?>" class="btn btn-default btn-lg step" value="Other Breeds" role="button"><?php echo $this->Word(85);?></a>
            </p>

		</div>

	</div>
</div>