<div class="panel">

	<h2>Results of Quick Search</h2>
	
	<div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Bull</th>
            <th>NAAB</th>
            <th>Registration Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($this->Results as $v) { ?>  
          <tr>
            <td><?php echo $v->f1 ; ?></td>
            <td><?php echo $v->f2 ; ?></td>
            <td><?php echo $v->f3 ; ?></td>
            <td>
              <a href="<?php echo $this->baseUrl() ?>/result/details/id/<?php echo $v->cod_bull ;?>" class="btn btn-sm btn-primary">
                        <i class="fa fa-list"></i> Detail
                    </a>
            </td>
          </tr>
        <?php } ?>  
        </tbody>
      </table>
    </div><!-- /.table-responsive -->


</div>