<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/default/js/maps.js"></script>

<h2>Contato</h2>

<section class="col-xs-12 col-sm-4 col-md-4">

	<?php echo $this->Msg; ?>
	<?php echo $this->Form; ?>
	<div class="clearfix"></div>	
</section>
	
<section class="col-sm-8 col-md-8">
		
	<div id="map-canvas"></div>
	
	<div class="location hidden-xs">
    	<div class="address">
        	<h3>Contato</h3>
            <p>Rua do Carmo, nº 580</p>
            <p>Bairro: Nossa Senhora da Abadia</p>
            <p>Cidade: Uberaba-MG</p>
            <p>CEP 38025-000</p>
        </div>
        <p><i class="icon-mobile-phone contact-icon"></i> <b>(34) 9171-0010 ( 24h para sinistro )</b></p>
        <p><i class="icon-phone contact-icon"></i> (34) 3331-0078</p>
        <p><i class="icon-envelope-alt contact-icon"></i><a href="mailto:laseg@lacorretora.com.br"> laseg@lacorretora.com.br</a></p>
     </div>
	
</section>

<div class="clearfix"></div>
