<div class="btn-group">
  <button class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-upload fa-lg"></i> Upload Excel Proof <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-success">
    <li><a href="<?php echo $this->BaseUrl() ?>/admin/proof/holstein">Holstein</a></li>
    
  </ul>
</div>

<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Proofs</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Breed</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php 
                    $Model_Breed = new Model_Breed();
                    foreach ($this->Data as $rs) { 
                        $breed = $Model_Breed->getBreedById($rs->breed);
                    ?>
                    <tr>
                        <td><?php echo $this->Data($rs->create_time); ?></td>
                        <td><?php echo $rs->name; ?></td>
                        <td><?php echo $breed->name; ?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->