<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/touro/new">
    <i class="fa fa-plus-circle fa-lg"></i> New Bull
</a>

<div class="btn-group">
  <button class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-download fa-lg"></i> Download Excel File <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-success">
    <li><a href="<?php echo $this->BaseUrl() ?>/admin/upload/Bull2.xls">Bulls</a></li>
    <li><a href="<?php echo $this->BaseUrl() ?>/admin/upload/goals.xls">Goals</a></li>
  </ul>
</div>

<div class="btn-group">
  <button class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-upload fa-lg"></i> Upload Excel File <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-success">
    <li><a href="<?php echo $this->BaseUrl() ?>/admin/touro/uploadbull">Bulls</a></li>
    <li><a href="<?php echo $this->BaseUrl() ?>/admin/touro/uploadgoal">Goals</a></li>
  </ul>
</div>



<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Bulls</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Bovine Id</th>
                        <th>NAAB2</th>
                        <th>Actions</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $rs->f1; ?></td>
                        <td><?php echo $rs->f36; ?></td>
                        <td><?php echo $rs->f2; ?></td>
                        
                        <td class="center">
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Additional Information" href="<?php echo $this->BaseUrl() ?>/admin/touro/information/id/<?php echo $rs->cod_bull ?>">
                                <i class="fa fa-list fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Edit" href="<?php echo $this->BaseUrl() ?>/admin/touro/edit/id/<?php echo $rs->cod_bull ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Images" href="<?php echo $this->BaseUrl() ?>/admin/touro/image/id/<?php echo $rs->cod_bull ?>">
                                <i class="fa fa-picture-o fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Videos" href="<?php echo $this->BaseUrl() ?>/admin/touro/video/id/<?php echo $rs->cod_bull ?>">
                                <i class="fa fa-youtube-play  fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Delete" href="<?= $this->BaseUrl() ?>/admin/touro/delete/id/<?php echo $rs->cod_bull; ?>" >
                                <i class="fa fa-trash-o fa-lg"></i> 
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/col-->
</div><!--/row-->