<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/portfolio/new">
    <i class="fa fa-plus-circle fa-lg"></i> New Portfolio
</a>

<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Portfolios</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $this->Data($rs->created_at); ?></td>
                        <td><?php echo $rs->name; ?></td>

                        <td class="center">
                            
                            <a class="btn btn-sm btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Bull List" href="<?php echo $this->BaseUrl() ?>/portfolio/bull/id/<?php echo $rs->cod_portfolio; ?>">
                                <i class="fa fa-list fa-lg"></i>  
                            </a>

                            <a class="btn btn-sm btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Send Portfolio E-mail" href="<?php echo $this->BaseUrl() ?>/portfolio/email/id/<?php echo $rs->cod_portfolio; ?>">
                                <i class="fa fa-envelope fa-lg"></i>  
                            </a>

                            <a class="btn btn-sm btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Edit" href="<?php echo $this->BaseUrl() ?>/portfolio/edit/id/<?php echo $rs->cod_portfolio; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>

                            <a class="btn btn-sm btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Create / Edit Cover" href="<?php echo $this->BaseUrl() ?>/portfolio/cover/id/<?php echo $rs->cod_portfolio; ?>">
                                 <i class="fa fa-file fa-lg"></i> 
                            </a> 

                            <a class="btn btn-sm btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Print Cover" href="<?php echo $this->BaseUrl() ?>/portfolio/print/id/<?php echo $rs->cod_portfolio; ?>" target="_blank">
                                 <i class="fa fa-print fa-lg"></i> 
                            </a> 

                            <a class="btn btn-sm btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Delete" href="<?= $this->BaseUrl() ?>/portfolio/delete/id/<?php echo $rs->cod_portfolio; ?>" >
                                <i class="fa fa-trash-o fa-lg"></i> 
	                        </a>

                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->