<div class="col-xs-12"> 
	<div class="table-header"><i class="fa fa-th-large"></i> Portfolio</div>     
	<br />
	<table width="100%" border="0" cellspacing="3" cellpadding="5">
		<tr>
			<td><b>Date</b></td>
		</tr>
		<tr>
			<td><?php echo $this->Data($this->Data->created_at);?></td>
		</tr>
		<tr>
			<td><b>Name</b></td>
		</tr>
		<tr>
			<td><?php echo $this->Data->name;?></td>
		</tr>
		<tr>
			<td><b>Information</b></td>
		</tr>
		<tr>
			<td><?php echo $this->Data->information;?></td>
		</tr>
		<tr>
			<td><b>Comment</b></td>
		</tr>
		<tr>
			<td><?php echo $this->Data->comments;?></td>
		</tr>
	</table>

	<br /><br />

	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Code</th>
				<th>Breed</th>
			</tr>
		</thead>   
		<tbody>
			<?php 

			$Model_Touro = new Model_Touro();
			$Model_Breed = new Model_Breed();

			foreach ($this->Bulls as $rs) { 

				$bull = $Model_Touro->getBullById($rs->bull);
				$breed = $Model_Breed->getBreedById($bull->breed);
				?>
				<tr>
					<td><?php echo $bull->f1; ?></td>
					<td><?php echo $bull->f2; ?></td>
					<td><?php echo $breed->name; ?></td>

				</tr>
				<?php } ?>
			</tbody>
		</table>     

	</div>
