<?php 

$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
$sessionStep = new Zend_Session_Namespace('sessionStep');
$image = '<img src="'.$this->baseUrl().'/default/imagens/check-white.jpg" class="" alt="" title=""> ';

$step1 =  false;
$step2 =  false;
$step3 =  false;
$step4 =  false;

if($action != 'step1' and !empty($sessionStep->step1)) {

	$step1 = true;
	$step1Label = '<a href="'.$this->baseUrl().'/index/step1" class="btn btn-primary btn-xs">'.$sessionStep->step1Label.'</a>';
}

if($action != 'step2' and !empty($sessionStep->step2)) {

	$step2 = true;
	$step2Label = '<a href="'.$this->baseUrl().'/index/step2" class="btn btn-primary btn-xs">'.$sessionStep->step2Label.'</a>';
}

if($action != 'step3' and !empty($sessionStep->step3)) {

	$step3 = true;
	$step3Label = '<a href="'.$this->baseUrl().'/index/step3" class="btn btn-primary btn-xs">'.$sessionStep->step3Label.'</a>';
}

if($action != 'step4' and !empty($sessionStep->step4)) {

	$step4 = true;

	if ($sessionStep->goalVolume == 1) {
		$label .= 'Volume <br />';
	} 
	if ($sessionStep->goalLongevity == 1) {
		$label .= 'Longevity <br />';
	} 
	if ($sessionStep->goalMilkFat == 1) {
		$label .= 'Milk components – Fat% <br /> ';
	}
	if ($sessionStep->goalMilkProtein == 1) {
		$label .= 'Milk components – Protein % <br /> ';
	}
	if ($sessionStep->goalDaughter == 1) {
		$label .= 'Daughter Fertility';
	}

	$step4Label = '<a href="'.$this->baseUrl().'/index/step4" class="btn btn-primary btn-xs">'.$label.'</a>';
}
	 
?>


<ul id="side-bar" class="list-unstyled col-xs-12 col-sm-6 col-md-3">
	<li>
		<?php if($step1) echo $image; ?>
		<a href="<?php echo $this->baseUrl() ?>/index/step1" class=""><?php echo $this->Word(75);?> / <?php echo $this->Word(76);?></a>
		<?php if($step1) echo $step1Label; ?>
	</li>
	<li>
		<?php if($step2) echo $image; ?>
		<a href="<?php echo $this->baseUrl() ?>/index/step2"><?php echo $this->Word(78);?></a>
		<?php if($step2) echo $step2Label; ?>
	</li>
	<li>
		<?php if($step3) echo $image; ?>
		<a href="<?php echo $this->baseUrl() ?>/index/step3"><?php echo $this->Word(79);?></a>
		<?php if($step3) echo $step3Label; ?>
	</li>
	<li>
		<?php if($step4) echo $image; ?>
		<a href="<?php echo $this->baseUrl() ?>/index/step4"><?php echo $this->Word(80);?></a>
		<?php if($step4) echo $step4Label; ?>
	</li>
	<li class="last">
		<a href="#">Go</a>
	</li>
</ul>  