<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/idioma/new">
    <i class="fa fa-plus-circle fa-lg"></i> New Language
</a>

<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Languages</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Language</th>
                        <th>Code</th>
                        <th>Published</th>
                        <th>Actions</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $rs->nome; ?></td>
                        <td><?php echo $rs->codigo; ?></td>
                        <td class="center">
                        	<?php 
                        		if($rs->situacao == 1) echo '<span class="label label-success arrowed">Yes</label'; else echo '<span class="label">No</label';
                        	?>
                        </td>
                        <td class="center">
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Edit" href="<?php echo $this->BaseUrl() ?>/admin/idioma/edit/id/<?php echo $rs->cod_language; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                            
                            <?php if($rs->padrao == 0) { ?>
                            
	                            <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Delete" href="<?= $this->BaseUrl() ?>/admin/idioma/delete/id/<?php echo $rs->cod_language; ?>" >
	                                <i class="fa fa-trash-o fa-lg"></i> 
	                            </a>
                            
                            <?php }  ?>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->