<div class="panel">

	<div class="panel-body">
		
		<p>
			Welcome to the ABS Global <br />
			Bull Search Application - Advanced Search.<br /><br />
		</p>

		<form role="form">
			  
			<div class="row">

				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
					<label for="breed">Breeds</label>
					<select name="breed" id="breed" class="form-control">
						<option value="">Select Breed</option>
						<?php foreach ($this->Breeds as $v) { ?>
						<option value="<?php echo $v->cod_breed; ?>"><?php echo $v->name; ?></option>
						<?php } ?>
					</select>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
					<label for="sire-type">Sire Type</label>
					<select name="sire-type" id="sire-type" class="form-control">
						<option value="">Select Sire Type</option>
						<option value="daughter_proven">Daughter Proven</option>
						<option value="genomic_young_sires">Genomic Young Sires</option>
					</select>
				</div>

				<br clear="all"><br clear="all">

				<div id="table-result" class="table-responsive">
	  				
				</div>

				<br clear="all">

				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
				
					<label for="abs">Bulls Type</label>
					<div class="radio">
						<label>
					    	<input type="radio" name="abs" id="abs-only" class="js-bullsType" value="1" checked>
					    	ABS Bulls Only
					 	</label>
					</div>

					<div class="radio">
						<label>
					    	<input type="radio" name="abs" id="abs-all" class="js-bullsType" value="0">
					    	All Bulls
					  	</label>
					</div>

				</div>

				<div id="selos" class="col-xs-12 col-sm-6 col-md-9 col-lg-9">

					<ul class="list-inline">
						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/breeders_choice.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Breeders Choice" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="breeders_choice">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/calving_ease.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="7.4% or Less Calving Ease" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="calving_ease">
						</li>


						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/diamond_sire.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Diamond Sire (1,000 Milking Dtrs)" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="diamond_sire">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/durabulls.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="DURAbulls (Health & Fitness Leaders)" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="durabulls">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/feed_efficieny.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Feed Efficiency Leader" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="feed_efficieny">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/judges_choice.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Judge’s Choice (High Type)" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="judges_choice">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/pregnancy_king.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="ABS Pregnancy Kings (Fertility Leaders)" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="pregnancy_king">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/redwhite.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Red and White" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="redwhite">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/sexation.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="ABS Sexation® - Sex Sorted Semen" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="sexation">
						</li>

						<li class="selos-adv">
							
					    	<img src="<?php echo $this->baseUrl() ?>/default/uploads/selos/sexation_only.jpg" width="50" height="50" class="img-responsive selos" data-toggle="tooltip" data-placement="top" title="Available Only in ABS Sexation®" />
					    	<br>
					    	<input type="checkbox" class="js-checkSelos" value="sexation_only">
						</li>
					</ul>	
				
					
					

				</div>

				<button type="button" id="js-advSearchStep" class="btn btn-primary pull-right">Search</button>

			</div>


		</form>

	</div>
</div>