<table width="100%" border="0" cellspacing="3" cellpadding="5">
  <tr>
    <td colspan="4" align="center" bgcolor="#CCCCCC"><strong>Password Reset</strong></td>
  </tr>
    <tr>
    <td width="16%">Name:</td>
    <td width="38%"><?php echo $this->dados["first_name"].' '.$this->dados["last_name"];?></td>
    <td width="18%">E-mail:</td>
      <td width="28%"><?php echo $this->dados["email"];?></td>
  </tr>
    <tr>
    <td colspan="4">Link to password reset</td>
    </tr>
    <tr>
      <td colspan="4">
        <a href="http://spring.bi/bullsearch/public_html/register/reset/id/<?php echo base64_encode($this->dados["cod_customer"]);?>">
          Click to access
        </a></td>
    </tr>
</table>