<table width="100%" border="0" cellspacing="3" cellpadding="5">
  <tr>
    <td align="center" bgcolor="#CCCCCC"><strong>Welcome - Genus Bull Search</strong></td>
  </tr>
  <tr>
    <td>
      <?php echo $this->dados["first_name"].' '.$this->dados["last_name"];?> thank your for registering with ABS.
      <br /><br />
      Your user name is: <?php echo $this->dados["email"];?><br />
      Your password is: <?php echo $this->dados["password"];?><br />
      <br />
      Find out more about ABS products and services from your salesperson or distributor, visit www.absglobal.com, or call (+1)800-ABS-STUD (+1-800-227-7883).  
    </td>
  </tr>
</table>