<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Customers</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Name (First + Last)</th>
                        <th>Country</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php 
                        $Model_Country = new Model_Country();
                        foreach ($this->Data as $rs) { 
                            $country = $Model_Country->getCountryById($rs->country);
                    ?>
                    <tr>
                        <td><?php echo $rs->first_name.' '.$rs->last_name; ?></td>
                        <td><?php echo $country->name; ?></td>
                        <td class="center">
                        <?php 
                        if($rs->type == 1) 
                            echo '<span class="label label-primary arrowed arrowed-right">Normal</label'; 
                        elseif($rs->type == 2)  
                            echo '<span class="label label-warning arrowed arrowed-right">ABS Employee</label';
                        elseif($rs->type == 3) 
                            echo '<span class="label label-info arrowed arrowed-right">Agent</label';
                        ?>
                        </td>
                        <td class="center">
                        <?php 
                        if($rs->status == 1) 
                            echo '<span class="label label-success arrowed arrowed-right">Active</label'; 
                        else 
                            echo '<span class="label label-warning arrowed arrowed-right">Inactive</label';
                        ?>
                        </td>
                        <td class="center">
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Edit" href="<?php echo $this->BaseUrl() ?>/admin/customer/edit/id/<?php echo $rs->cod_customer; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                             <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Delete" href="<?= $this->BaseUrl() ?>/admin/customer/delete/id/<?php echo $rs->cod_customer; ?>" >
                                <i class="fa fa-trash-o fa-lg"></i> 
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->